[build]
  publish = "dist"
  command = "yarn install && yarn build && yarn generate"

[build.environment]
  CI = "1"
  NODE_VERSION = "18"
  NODE_OPTIONS = "--max-old-space-size=4096"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["jsdom"]
