[build]
  publish = "dist"
  command = "yarn generate"

[build.environment]
  CI = "1"
  NODE_VERSION = "23.11.0"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["jsdom"]
